name: React CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies, build and deploy
      run: |
        yarn install
        git config --global user.email "sshyam-gupta@users.noreply.github.com"
        git config --global user.name "Shyam Gupta"
        git remote set-url origin https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@github.com/sshyam-gupta/${{ secrets.GITHUB_REPOSITORY }}.git
        yarn deploy
