name: React CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies, build
      run: |
        yarn install
        yarn build
    - name: Publish to surge.sh
      uses: dswistowski/surge-sh-action@v1.0.0
      with:
        domain: 'redundant-sun.surge.sh'
        login: shyamm@outlook.com
        token: ${{ secrets.SURGE_TOKEN }}
        project: 'build/'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

