name: React CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies, build and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      run: |
        yarn install
        yarn build
        git config --global user.email "shyamsundar.g@kiprosh.com"
        git config --global user.name "Shyam Gupta"
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        yarn run deploy

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
